### ISSUE TITLE
Add dependency to "ScanditCaptureCore API"

### ISSUE THREAD

**Issue by chbeer** [Scandit/datacapture-spm-barcode#2]
Since Swift Package Manager is a *dependency* manager, please add a dependency to `https://github.com/Scandit/datacapture-spm-core.git` in the Package.swift, instead of the description.

**Comment by lucatorella** [comment]
This is currently not possible. Binary targets don't support dependencies at the moment. 

https://forums.swift.org/t/swiftpm-binary-target-with-sub-dependencies/40197
