### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by chbeer** [Scandit/datacapture-spm-barcode#3]
The documentation found here: https://docs.scandit.com/data-capture-sdk/ios/get-started-barcode.html

Seems out of date. At least the following commands did change:

`camera?.applySettings(cameraSettings)`
is now
`camera?.apply(cameraSettings)`

and 

`captureView.dataCaptureContext`
is now
`captureView.context`

**Comment by lucatorella** [comment]
Thanks @chbeer, you are absolutely right. Docs will be fixed with the next release.
